[2025-01-12T17:50:45.110+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.install_library manual__2025-01-12T17:45:42.674497+00:00 [queued]>
[2025-01-12T17:50:45.119+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.install_library manual__2025-01-12T17:45:42.674497+00:00 [queued]>
[2025-01-12T17:50:45.119+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T17:50:45.119+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2025-01-12T17:50:45.119+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T17:50:45.127+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): install_library> on 2025-01-12 17:45:42.674497+00:00
[2025-01-12T17:50:45.132+0000] {standard_task_runner.py:52} INFO - Started process 732 to run task
[2025-01-12T17:50:45.134+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coin_scrapper2', 'install_library', 'manual__2025-01-12T17:45:42.674497+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/AirflowCrypto2.py', '--cfg-path', '/tmp/tmpd_5byq60', '--error-file', '/tmp/tmp9yge4l9q']
[2025-01-12T17:50:45.135+0000] {standard_task_runner.py:80} INFO - Job 11: Subtask install_library
[2025-01-12T17:50:45.210+0000] {task_command.py:371} INFO - Running <TaskInstance: coin_scrapper2.install_library manual__2025-01-12T17:45:42.674497+00:00 [running]> on host a71d0af9bc73
[2025-01-12T17:50:45.274+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=terry
AIRFLOW_CTX_DAG_ID=coin_scrapper2
AIRFLOW_CTX_TASK_ID=install_library
AIRFLOW_CTX_EXECUTION_DATE=2025-01-12T17:45:42.674497+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-12T17:45:42.674497+00:00
[2025-01-12T17:50:45.275+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-12T17:50:45.276+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/extract2.py']
[2025-01-12T17:50:45.284+0000] {subprocess.py:85} INFO - Output:
[2025-01-12T17:50:45.550+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-01-12T17:50:45.550+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
[2025-01-12T17:50:45.652+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-12T17:50:45.654+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract2.py", line 25, in <module>
[2025-01-12T17:50:45.654+0000] {subprocess.py:92} INFO -     main()
[2025-01-12T17:50:45.654+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract2.py", line 9, in main
[2025-01-12T17:50:45.654+0000] {subprocess.py:92} INFO -     .appName("PySpark Example") \
[2025-01-12T17:50:45.654+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2025-01-12T17:50:45.654+0000] {subprocess.py:92} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-01-12T17:50:45.655+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 384, in getOrCreate
[2025-01-12T17:50:45.655+0000] {subprocess.py:92} INFO -     SparkContext(conf=conf or SparkConf())
[2025-01-12T17:50:45.655+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 144, in __init__
[2025-01-12T17:50:45.655+0000] {subprocess.py:92} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-01-12T17:50:45.655+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 331, in _ensure_initialized
[2025-01-12T17:50:45.655+0000] {subprocess.py:92} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-01-12T17:50:45.655+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2025-01-12T17:50:45.656+0000] {subprocess.py:92} INFO -     raise Exception("Java gateway process exited before sending its port number")
[2025-01-12T17:50:45.656+0000] {subprocess.py:92} INFO - Exception: Java gateway process exited before sending its port number
[2025-01-12T17:50:45.686+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-12T17:50:45.710+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-12T17:50:45.722+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=coin_scrapper2, task_id=install_library, execution_date=20250112T174542, start_date=20250112T175045, end_date=20250112T175045
[2025-01-12T17:50:45.736+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task install_library (Bash command failed. The command returned a non-zero exit code 1.; 732)
[2025-01-12T17:50:45.781+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-12T17:50:45.846+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
