[2025-01-12T17:55:02.588+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:45:00+00:00 [queued]>
[2025-01-12T17:55:02.593+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:45:00+00:00 [queued]>
[2025-01-12T17:55:02.593+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T17:55:02.594+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2025-01-12T17:55:02.594+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T17:55:02.601+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): install_library> on 2025-01-12 17:45:00+00:00
[2025-01-12T17:55:02.605+0000] {standard_task_runner.py:52} INFO - Started process 280 to run task
[2025-01-12T17:55:02.607+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coin_scrapper2', 'install_library', 'scheduled__2025-01-12T17:45:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/AirflowCrypto2.py', '--cfg-path', '/tmp/tmpd8wu5vgl', '--error-file', '/tmp/tmponeaiige']
[2025-01-12T17:55:02.608+0000] {standard_task_runner.py:80} INFO - Job 15: Subtask install_library
[2025-01-12T17:55:02.657+0000] {task_command.py:371} INFO - Running <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:45:00+00:00 [running]> on host a71d0af9bc73
[2025-01-12T17:55:02.694+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=terry
AIRFLOW_CTX_DAG_ID=coin_scrapper2
AIRFLOW_CTX_TASK_ID=install_library
AIRFLOW_CTX_EXECUTION_DATE=2025-01-12T17:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-12T17:45:00+00:00
[2025-01-12T17:55:02.694+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-12T17:55:02.695+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/extract2.py']
[2025-01-12T17:55:02.700+0000] {subprocess.py:85} INFO - Output:
[2025-01-12T17:55:03.004+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-01-12T17:55:03.005+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
[2025-01-12T17:55:03.090+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-12T17:55:03.090+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract2.py", line 23, in <module>
[2025-01-12T17:55:03.090+0000] {subprocess.py:92} INFO -     main()
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract2.py", line 7, in main
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -     .appName("PySpark Example") \
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 384, in getOrCreate
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -     SparkContext(conf=conf or SparkConf())
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 144, in __init__
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 331, in _ensure_initialized
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO -     raise Exception("Java gateway process exited before sending its port number")
[2025-01-12T17:55:03.091+0000] {subprocess.py:92} INFO - Exception: Java gateway process exited before sending its port number
[2025-01-12T17:55:03.114+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-12T17:55:03.127+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-12T17:55:03.130+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=coin_scrapper2, task_id=install_library, execution_date=20250112T174500, start_date=20250112T175502, end_date=20250112T175503
[2025-01-12T17:55:03.139+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task install_library (Bash command failed. The command returned a non-zero exit code 1.; 280)
[2025-01-12T17:55:03.172+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-12T17:55:03.202+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
