[2025-01-12T17:30:20.554+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:25:00+00:00 [queued]>
[2025-01-12T17:30:20.562+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:25:00+00:00 [queued]>
[2025-01-12T17:30:20.562+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T17:30:20.562+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-01-12T17:30:20.562+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T17:30:20.571+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): install_library> on 2025-01-12 17:25:00+00:00
[2025-01-12T17:30:20.575+0000] {standard_task_runner.py:52} INFO - Started process 199 to run task
[2025-01-12T17:30:20.579+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coin_scrapper2', 'install_library', 'scheduled__2025-01-12T17:25:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/AirflowCrypto2.py', '--cfg-path', '/tmp/tmp0beypw5u', '--error-file', '/tmp/tmpld69k8kq']
[2025-01-12T17:30:20.580+0000] {standard_task_runner.py:80} INFO - Job 3: Subtask install_library
[2025-01-12T17:30:20.660+0000] {task_command.py:371} INFO - Running <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:25:00+00:00 [running]> on host 8c3d2ee7eb21
[2025-01-12T17:30:20.725+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=terry
AIRFLOW_CTX_DAG_ID=coin_scrapper2
AIRFLOW_CTX_TASK_ID=install_library
AIRFLOW_CTX_EXECUTION_DATE=2025-01-12T17:25:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-12T17:25:00+00:00
[2025-01-12T17:30:20.726+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-12T17:30:20.727+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/extract2.py']
[2025-01-12T17:30:20.741+0000] {subprocess.py:85} INFO - Output:
[2025-01-12T17:30:21.203+0000] {subprocess.py:92} INFO - JAVA_HOME is not set
[2025-01-12T17:30:21.295+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-12T17:30:21.298+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract2.py", line 23, in <module>
[2025-01-12T17:30:21.298+0000] {subprocess.py:92} INFO -     main()
[2025-01-12T17:30:21.300+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract2.py", line 7, in main
[2025-01-12T17:30:21.301+0000] {subprocess.py:92} INFO -     .master("local[*]") \
[2025-01-12T17:30:21.302+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2025-01-12T17:30:21.304+0000] {subprocess.py:92} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-01-12T17:30:21.306+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 384, in getOrCreate
[2025-01-12T17:30:21.307+0000] {subprocess.py:92} INFO -     SparkContext(conf=conf or SparkConf())
[2025-01-12T17:30:21.308+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 144, in __init__
[2025-01-12T17:30:21.309+0000] {subprocess.py:92} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-01-12T17:30:21.310+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 331, in _ensure_initialized
[2025-01-12T17:30:21.311+0000] {subprocess.py:92} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-01-12T17:30:21.311+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2025-01-12T17:30:21.311+0000] {subprocess.py:92} INFO -     raise Exception("Java gateway process exited before sending its port number")
[2025-01-12T17:30:21.311+0000] {subprocess.py:92} INFO - Exception: Java gateway process exited before sending its port number
[2025-01-12T17:30:21.318+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-12T17:30:21.331+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-12T17:30:21.333+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=coin_scrapper2, task_id=install_library, execution_date=20250112T172500, start_date=20250112T173020, end_date=20250112T173021
[2025-01-12T17:30:21.340+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task install_library (Bash command failed. The command returned a non-zero exit code 1.; 199)
[2025-01-12T17:30:21.380+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-12T17:30:21.402+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
