[2025-01-12T17:40:00.384+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:35:00+00:00 [queued]>
[2025-01-12T17:40:00.391+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:35:00+00:00 [queued]>
[2025-01-12T17:40:00.391+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T17:40:00.391+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-01-12T17:40:00.391+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-12T17:40:00.397+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): install_library> on 2025-01-12 17:35:00+00:00
[2025-01-12T17:40:00.401+0000] {standard_task_runner.py:52} INFO - Started process 315 to run task
[2025-01-12T17:40:00.405+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coin_scrapper2', 'install_library', 'scheduled__2025-01-12T17:35:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/AirflowCrypto2.py', '--cfg-path', '/tmp/tmpwf4wwj5f', '--error-file', '/tmp/tmpc6pakxoi']
[2025-01-12T17:40:00.406+0000] {standard_task_runner.py:80} INFO - Job 4: Subtask install_library
[2025-01-12T17:40:00.520+0000] {task_command.py:371} INFO - Running <TaskInstance: coin_scrapper2.install_library scheduled__2025-01-12T17:35:00+00:00 [running]> on host a71d0af9bc73
[2025-01-12T17:40:00.569+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=terry
AIRFLOW_CTX_DAG_ID=coin_scrapper2
AIRFLOW_CTX_TASK_ID=install_library
AIRFLOW_CTX_EXECUTION_DATE=2025-01-12T17:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-12T17:35:00+00:00
[2025-01-12T17:40:00.571+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-12T17:40:00.572+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/extract2.py']
[2025-01-12T17:40:00.579+0000] {subprocess.py:85} INFO - Output:
[2025-01-12T17:40:00.891+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-01-12T17:40:00.892+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
[2025-01-12T17:40:00.988+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-12T17:40:00.988+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract2.py", line 22, in <module>
[2025-01-12T17:40:00.989+0000] {subprocess.py:92} INFO -     main()
[2025-01-12T17:40:00.989+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract2.py", line 6, in main
[2025-01-12T17:40:00.989+0000] {subprocess.py:92} INFO -     .appName("PySpark Example") \
[2025-01-12T17:40:00.989+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2025-01-12T17:40:00.989+0000] {subprocess.py:92} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-01-12T17:40:00.989+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 384, in getOrCreate
[2025-01-12T17:40:00.989+0000] {subprocess.py:92} INFO -     SparkContext(conf=conf or SparkConf())
[2025-01-12T17:40:00.990+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 144, in __init__
[2025-01-12T17:40:00.990+0000] {subprocess.py:92} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-01-12T17:40:00.990+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 331, in _ensure_initialized
[2025-01-12T17:40:00.990+0000] {subprocess.py:92} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-01-12T17:40:00.990+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2025-01-12T17:40:00.991+0000] {subprocess.py:92} INFO -     raise Exception("Java gateway process exited before sending its port number")
[2025-01-12T17:40:00.991+0000] {subprocess.py:92} INFO - Exception: Java gateway process exited before sending its port number
[2025-01-12T17:40:01.015+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-12T17:40:01.028+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-12T17:40:01.035+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=coin_scrapper2, task_id=install_library, execution_date=20250112T173500, start_date=20250112T174000, end_date=20250112T174001
[2025-01-12T17:40:01.045+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task install_library (Bash command failed. The command returned a non-zero exit code 1.; 315)
[2025-01-12T17:40:01.056+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-12T17:40:01.080+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
